### ISSUE TITLE
Post schema 4.0.0 release checklist

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/hubUtils#190]
- [ ] remove `br-v4.0.0` mention
- [ ] add back ` (>= 0.2.0.9000)` as a minimum version requirement for `hubUtils`
- [ ] remove pull request remote reference for `hubUtila`
- [ ] re-snapshot
